project:
  type: website
  output-dir: docs

website:
  title: "Trang Ly"
  navbar:
    background: light
    foreground: dark
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Get in Touch!
        menu:
          - href: mailto:trangly48@gmail.com
            text: Email
          - href: https://www.linkedin.com/in/trang-t-ly
            text: LinkedIn

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true

editor: visual

